### ISSUE TITLE
Can't consume kslides

### ISSUE THREAD

**Issue by andylamax** [kslides/kslides#12]
adding kslides as maven dependency to a project succeeds but downloads an empty jar with just manifest.

It is either you are publishing an empty jar, or jitpack is serving an empty jar.

**Comment by pambrose** [comment]
That is not cool. Let me try it with Maven.

**Comment by pambrose** [comment]
I created a Maven version of a slideshow, and it works. However, Maven requires 2 additional dependencies to be included (which I guess gradle imports automatically). Try adding these two and see what happens:

```
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-html-jvm</artifactId>
            <version>0.7.5</version>
        </dependency>
```
and
```
        <dependency>
            <groupId>org.jetbrains.kotlin-wrappers</groupId>
            <artifactId>kotlin-css</artifactId>
            <version>1.0.0-pre.343</version>
        </dependency>
```

**Comment by pambrose** [comment]
This is the pom.xml I used: https://gist.github.com/pambrose/ecf7021f5e3abc785a81bed3241a2b2b

**Comment by andylamax** [comment]
Adding kotlin-css and kotlinx-html as gradle dependencies only resolves them. I am still failing to use kslides. Even importing from `com.kslides.*` fails. Have you tried consuming with gradle? or does this just work with maven?

**Comment by pambrose** [comment]
This repo uses gradle with kslides: https://github.com/kslides/kslides-template

I updated the gist above, which has the pom.xml  you need to use maven. 

Clone the repo above and it should work fine.

**Comment by andylamax** [comment]
Looking at the template I see where I had it wrong. jitpack instructs to the wrong coordinates. following the link to jitpack, it directs one to include kslides as `com.github.kslides.kslides:kslides:<VERSION>` instead of `com.github.kslides.kslides:kslides-core:<VERSION>`. Maybe these coordinates should be somewhere in the README.md to avoid future confusions?

**Comment by pambrose** [comment]
I added a note to the README.md. Thanks.
