### ISSUE TITLE
Split kslides into multiple submodules that on can opt in

### ISSUE THREAD

**Issue by andylamax** [kslides/kslides#13]
At the moment, kslides-core, holds implementation of every plugin and add on. This is not convenient for someone who just needs something basic.

e.g. For someone who doesn't even need to utilize plots (and the plotykt library), has no option bu to bring in the whole plotykt train when they add `kslides-core` as a dependency.

I haven't gone through the whole code base, but I think it might be a good idea to split these and let them be added as add ons.

`kslides-core`, can have just the kslides block and other `core` functionality as the name implies. Other modules like using plotykt or `kotlin-playground`(assuming it brings in third-party dependencies) can be optional dependencies store into a module like `kslides-ploty` (or something similar).

In the end, we will have `kslides-core` as only a core dependency, and other add ons to be added only when needed.

Also, kslides require some transitive dependencies to be included by the consumer. This is a little bit tedious, we can leverage the amount of transitive dependencies and yet include them all without requiring additional dependencies (especially transitive ones)

**Comment by pambrose** [comment]
I agree, they should be split out. I will work on it this week. Thanks!

**Comment by andylamax** [comment]
Hello there, is there a contribution guide I can read about this so that I may be able to contribute?

**Comment by pambrose** [comment]
Sorry, I am afraid no such guide exists.

**Comment by andylamax** [comment]
So, does that mean I can't contribute?

**Comment by pambrose** [comment]
You are free to contribute. Just submit a PR.

**Comment by pambrose** [comment]
I separated plotly-kt support into a separate module: `com.github.kslides.kslides:kslides-plotly`
