### ISSUE TITLE
Setting topRightSvg doesn't do anything

### ISSUE THREAD

**Issue by xxfast** [kslides/kslides#16]
Hi

I've set my svg as 
```kotlin
presentationConfig {
  topRightHref = "/" 
  topRightTitle = "Home"
  topRightSvg = "images/home.svg"
  topRightText = ""
}
```
I've included the asset in `resource/public/images/home.svg` (and it is also included in the `docs` folder as well)

Is this the right way to do this? If so, this doesn't seem to work 

However, setting the background image in `slideConfig` does work 
```
slideConfig {
  backgroundImage = "images/home.svg"
}
```

**Comment by pambrose** [comment]
Ugh. I see the problem. Let me cut a new release.

**Comment by pambrose** [comment]
Actually, it was not the dumb mistake I thought that it was. The topRightSvg and topLeftSvg were meant to be assigned the actual svg tag details, e.g., https://github.com/kslides/kslides/blob/d1091eee15884176be9a389b80b6c6ad81fe322b/kslides-core/src/main/kotlin/com/kslides/config/PresentationConfig.kt#L325-L330

I will add a topLeftSvgSrc and topRightSvgSrc to accommodate your usage.

**Comment by pambrose** [comment]
Okay, update your gradle.properties to use kslides_version=0.13.1 and use `topRightSvgSrc`

**Comment by xxfast** [comment]
Awesome 🙌 thanks for the quick response. Looks like setting the svg directly with `topRightSvgSrc` will set the image correctly, but won't apply any styling, and the hense the size will be 0. Is this intended? 
<img width="1199" alt="Screen Shot 2022-08-31 at 9 34 45 am" src="https://user-images.githubusercontent.com/13775137/187561752-042760cc-a648-4421-a1c1-2ed54b422013.png">

Not sure if this is something you can fix with custom styling as the element doesn't have a class of it's own
<img width="1199" alt="Screen Shot 2022-08-31 at 9 35 21 am" src="https://user-images.githubusercontent.com/13775137/187561817-9407ec4c-bc98-4d00-976f-d0f5d7f3ec57.png">

**Comment by xxfast** [comment]
Not sure if #18 is the direction you want to handle this issue

**Comment by pambrose** [comment]
Yes, you are obviously right! Sorry about that. I added topLeftSvgClass, topLeftSvgStyle, topRightSvgClass, and topRightSvgStyle attributes. If the Class attributes are blank, then they default to "top-left-svg" and "top-right-svg"
I hope those do the trick. 
Thanks for the PR!
