### ISSUE TITLE
ConcurrentModificationException gets thrown if a Presentation.extension() contains verticalSlides inside of which you call  Presentation.anotherExtension()

### ISSUE THREAD

**Issue by Filip-FK-Kwiatkowski** [kslides/kslides#21]
Consider the following code that *works*:
```kotlin
fun main() {
    kslides {
        output {
            enableFileSystem = true
            enableHttp = false
        }

        presentation {
            path = "some/path/to/file.html"

            presentationConfig {
                transition = Transition.SLIDE
                transitionSpeed = Speed.SLOW
                theme = PresentationTheme.SKY
            }
                
            content()
        }
    }
}

fun Presentation.content() {
    verticalSlides {
        dslSlide {
            content { }
        }

        dslSlide {
            content { }
        }
    }
}
```
Inside `kslides { }` we call `content()` which is an extension function for `Presentation`. However, if we put `verticalSlides { }` inside that function and put *another extension function inside*:
```kotlin
fun main() {
    kslides {
        output {
            enableFileSystem = true
            enableHttp = false
        }

        presentation {
            path = "some/path/to/file.html"

            presentationConfig {
                transition = Transition.SLIDE
                transitionSpeed = Speed.SLOW
                theme = PresentationTheme.SKY
            }

            content()
        }
    }
}

fun Presentation.content() {
    verticalSlides {
        dslSlide {
            content { }
        }
//        Moved to extension function
//        dslSlide {
//            content { }
//        }
        nestedContent()
    }
}

fun Presentation.nestedContent() {
    dslSlide {
        content { }
    }
}
```
This no longers works and produces `java.util.ConcurrentModificationException`.

The full stack trace is as follows:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.kslides.Page.generateBody(Page.kt:433)
	at com.kslides.Page.access$generateBody(Page.kt:11)
	at com.kslides.Page.generatePage$kslides_core(Page.kt:22)
	at com.kslides.KSlides$Companion.writeSlidesToFileSystem$kslides_core(KSlides.kt:160)
	at com.kslides.KSlidesKt.kslides(KSlides.kt:69)
	at PJCSlidesKt.main(MyFile.kt:6)
	at PJCSlidesKt.main(MyFile.kt)
```
Where `MyFile.kt:6` is the initial `kslides { }` call.

I have not been able to find either a solution or a reason for why this happens. I consulted this problem with a more experienced Kotlin developer (however he was unfamiliar with kslides initially) and he suggested that the internal representation of extension functions may introduce problems if the internal implementation synchronizes some reads / writes on `this` (since extension methods get compiled to whole new classes).

Currently it's not a huge deal, but I wanted to create a presentation for the entire academic course using kslides and the inability to conveniently split parts of said presentation proves to clutter the code a bit.

The most interesting thing is that I recall this actually working, until it, well, stopped. I *think* it was after I upgraded to **Kotlin 1.7.20**. Could be the case that there was a data race there the whole time but only after some implementations changed in the new version, the problem started to manifest more evidently.

Another guess is that the extension function doesn't know that it will be called in the context of `verticalSlides { }`. I didn't manage to find anything in its implementation to indicate that `dslSlide { }` would result in something else compared to being called in a "pure" `Presentation` context. If that is the case, is there a way to create a `Presentation` extension that encapsulates the closure of `verticalSlides { }` too?

**Comment by Filip-FK-Kwiatkowski** [comment]
Trying to import both `Presentation` and `VerticalSlidesContext` into one scope by using:
```kotlin
fun Presentation.content() {
    verticalSlides {
        dslSlide {
            content { }
        }
//        Moved to extension function
//        dslSlide {
//            content { }
//        }
        nestedContent(this@content)
    }
}

fun VerticalSlidesContext.nestedContent(presentation: Presentation) = with(presentation) {
    dslSlide {
        content { }
    }
}
```
yields the same error.

**Comment by pambrose** [comment]
Hi Filip,

The issue is there are two dslSlide() calls: VerticalSlidesContext.dslSlide() and Presentation.dslSlide()
Prior to moving the dslSlide() call to an extension function, you are calling it in the context of VerticalSlidesContext.
With the extension function, you are calling it in the context of Presentation. Calling the Presentation version of dslSlide()
in the context of a VerticalSlide causes bookkeeping problems (as you saw). 

The solution is easy. The extension function should be defined as:
```
fun Presentation.nestedContent(verticalSlidesContext: VerticalSlidesContext) {
  verticalSlidesContext.dslSlide {
    content {
      h1 { +"I am here" }
    }
  }
}
```

and invoked with:
```
    nestedContent(this)  // where this is the VerticalSlidesContext of verticalSlides{}
```

Please let me know if this addresses your problem. If you still have unnecessary clutter, please let me know and we can get it right. 

Cheers,
Paul

**Comment by Filip-FK-Kwiatkowski** [comment]
Very interesting. It's still a little shady for me how exactly both of those contexts interact with one another, especially with extension functions involved. Must be my inexperience with the internal implementations of DSLs in Kotlin.

Nonetheless it completely solved my problem and my presentation is now neatly divided into functions, thank you!

One last thing - I am not knowledgeable enough in Kotlin to determine such thing, but maybe it would be a good idea to include this example in the README? It certainly was not obvious for me why extentind `Presentation` and passing `VerticalSlidesContext` solved the issue, but extending `VerticalSlidesContext` and passing `Presentation` did not.

Either way, thank you very much!

**Comment by pambrose** [comment]
Yes, it is an interesting situation when you have multiple applicable `this` values. The Kotlin 1.6.20 release previewed context receivers, which help with the case of multiple `this`values. I have not added context receivers to kslides because they are not supported in libraries (that may have since changed). 

Also, the confusion you went through would have been avoided had I used a different name for dslSlide{} in the VerticalSlide context, but that muddies things up when you move slides around. 

I will add a note about this to the README.

If your slides are public, please send me a link so I can show them as an example of what is possible. 

Thanks,
Paul

**Comment by Filip-FK-Kwiatkowski** [comment]
The presentation slides will be published in September. If, by that time, you will still be interested, I will happily share the link :>

I believe that using the same name (`dslSlide`) in both contexts was a good choice. Unfortunate that such pitfalls exist, but I think it's worth the consistency.

**Comment by pambrose** [comment]
I added a note to README.md, and yes, I would appreciate you sending a link to pambrose@mac.com when you finish them.

Thanks.
