### ISSUE TITLE
kslides appears as a JS project on GitHub

### ISSUE THREAD

**Issue by aSemy** [kslides/kslides#24]
When I look at kslides on GitHub, it's automatically given a JavaScript icon.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/897017/205621084-119b1585-de26-4f9e-8296-0ee36e7987d1.png">

I think this should instead show a Kotlin indicator 
<img width="60" alt="image" src="https://user-images.githubusercontent.com/897017/205622185-fa6e6987-7b02-48a7-8454-f0b83ca8aa81.png">

GitHub can be instructed to ignore JavaScript files using the `.gitattributes` file https://stackoverflow.com/a/43520676/4161471

**Comment by pambrose** [comment]
Absolutely!!! Thanks!
